export const CREATE_CABELEIREIRO = "CREATE_CABELEIREIRO";
export const FETCH_CABELEIREIRO = "FETCH_CABELEIREIRO";
export const FETCH_ALL_CABELEIREIROS = "FETCH_ALL_CABELEIREIROS";
export const EDIT_CABELEIREIRO = "EDIT_CABELEIREIRO";
export const DELETE_CABELEIREIRO = "DELETE_CABELEIREIRO";

export const FETCH_ALL_CLIENTES = "FETCH_ALL_CLIENTES";
export const FETCH_CLIENTE = "FETCH_CLIENTE";
export const CREATE_CLIENTE = "CREATE_CLIENTE";
export const EDIT_CLIENTE = "CREATE_CLIENTE";
export const DELETE_CLIENTE = "DELETE_CLIENTE";
export const FETCH_CLIENTE_NAME = "FETCH_CLIENTE_NAME";

export const FETCH_ALL_PRODUTOS = "FETCH_ALL_PRODUTOS";
export const FETCH_PRODUTO = "FETCH_PRODUTO";
export const CREATE_PRODUTO = "CREATE_PRODUTO";
export const EDIT_PRODUTO = "EDIT_PRODUTO";
export const DELETE_PRODUTO = "DELETE_PRODUTO";
export const FETCH_PRODUTO_NAME = "FETCH_PRODUTO_NAME";

export const FETCH_ALL_SERVICOS = "FETCH_ALL_SERVICOS";
export const FETCH_SERVICO = "FETCH_SERVICO";
export const CREATE_SERVICO = "CREATE_SERVICO";
export const EDIT_SERVICO = "EDIT_SERVICO";
export const DELETE_SERVICO = "DELETE_SERVICO";
export const FETCH_SERVICO_NAME = "FETCH_SERVICO_NAME";